language: php
php:
 - 5.5

env:
  global:
    secure: dXa39Ew3RGgQmQ5uyNPFN/kRQorXqMR8Cc0FPcO9fm/q8tlAT5Nl5QHvgU+Ext7KcSVeWHKnR2kSEd0Ciy1EDBxCcCWqpZBe94uYuYhogBraaRWcllC6SJGNgOEtinp01GJxnEnOfhPfJZbxa9pkN7snq9jPZYlRKcF5b4mBhxY=

install:
 - sudo apt-get install graphviz
 - composer install --prefer-dist --dev
 - npm install -g grunt-cli
 - npm install

script:
 - grunt test

after_success:
 - grunt docs